---
title: "FiguresForTrends"
author: "Catarina Pien"
date: "1/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(viridis)
```

```{r}
theme_fig = theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, size = 14),
        strip.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 11))

theme_figure <-  theme_bw() + theme(axis.title.y = element_blank(),                                 axis.title.x = element_blank(),legend.position = "right",
                                     axis.text.x = element_text(size = 10, angle= 90),
                                     axis.text.y = element_text(size = 10),
                                    legend.text = element_text(size = 10),
                                    legend.title = element_text(size = 10.5),
                                    plot.title = element_text(hjust = 0.5)) 
```

```{r}
tempDaily20 <- readRDS(here::here("Data/tempDaily20yr_20220125.rds")) %>%
  mutate(Region = as.character(Region)) %>%
  mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
         Region = replace(Region, Region == "San Joaquin", "Central")) %>%
  rename(WYType = WYType2_Sac)

tempDaily10 <- readRDS(here::here("Data/tempDaily_20210811.rds"))%>%
  mutate(Region = as.character(Region)) %>%
  mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
         Region = replace(Region, Region == "San Joaquin", "Central"))

LatLon <- read.csv(here::here("Data/StationsMetadata.csv"))

Regions <- read.csv(here::here("Data/Stations_wRosiesReg.csv")) %>%
  dplyr::select(-Latitude, -Longitude) %>%
  mutate(Region = as.character(Region)) %>%
  mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
         Region = replace(Region, Region == "San Joaquin", "Central"))
```

Station dates 
```{r}
first(tempDaily20$Date)
last(tempDaily20$Date)

first(tempDaily8$Date)
last(tempDaily20$Date)

str(tempDaily20)
str(tempDaily8)
```

Make supplemental tables
```{r}
summary20 <- tempDaily20 %>%
  group_by(Station) %>%
  summarize(StartDateAnalysis = first(Date),
            EndDateAnalysis = last(Date)) %>%
  left_join(LatLon %>% dplyr::select(Station, StationName, Agency, Latitude, Longitude, HabitatType)) %>%
  left_join(Regions %>% dplyr::select(Station, Region)) %>%
  dplyr::select(Station, StationName, Region, Latitude, Longitude, StartDateAnalysis, EndDateAnalysis, Agency, HabitatType)

#write_csv(summary20, "Tables/Stations_included_20year.csv")
summary10 <- tempDaily10 %>%
  group_by(Station) %>%
  summarize(StartDateAnalysis = first(Date),
            EndDateAnalysis = last(Date)) %>%
  left_join(LatLon %>% select(Station, StationName, Agency, Latitude, Longitude, HabitatType)) %>%
  left_join(Regions %>% select(Station, Region)) %>%
  select(Station, StationName, Region, Latitude, Longitude, StartDateAnalysis, EndDateAnalysis, Agency, HabitatType)

#write_csv(summary10, "Tables/Stations_included_10year.csv")
```

# 20 year trends
Grouping and means for max temp
```{r}
tempDaily20b <- tempDaily20 %>%
  mutate(Region2 = ifelse(Region == "Far North", "North Delta", Region),
         Month = month(Date),
         fWY = factor(WY),
         Season = ifelse(Month >4 & Month <10, "Dry Season", "Wet Season")) %>%
  mutate(Region2 = factor(Region2))

tempDaily20Summary <- tempDaily20b %>%
  group_by(fWY, WY, WYType, Region, Region2, Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily)) %>%
  ungroup()

tempSeason20SummaryStation <- tempDaily20b %>%
  group_by(Season, fWY, WY, WYType, Region, Region2,Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

tempSeason20Summary <- tempDaily20b %>%
  group_by(Season, fWY, WY, WYType, Region, Region2) %>%
  summarize(meanMaxTemp = mean(maxDaily, na.rm = TRUE),
            meanMinTemp = mean(minDaily, na.rm = TRUE),
            sd = sd(maxDaily, na.rm = TRUE),
            n = n(),
            se = sd/sqrt(n))
```

# Models
```{r}

South <- tempDaily20b %>%
  filter(Region == "South",
         Season == "Dry Season", fWY == "2017")

South <- tempSeason20SummaryStation %>%
  filter(Region == "South",
         Season == "Dry Season")

ggplot(South) + geom_point(aes(Date, maxDaily, color = Station)) + geom_line(aes(x =Date, y = maxDaily, color = Station))




```

```{r}
m1 <- lm(meanMaxTemp ~ Region * fWY, data = tempDaily20Summary)
anova(m1)
summary(m1)
plot(m1)


m2 <- lm(meanMaxTemp ~ Region2* fWY, data = tempDaily10Summary)
anova(m2)
summary(m2)
plot(m2)

# Variability 
m3 <- lm(cv ~ Region2*Season, data = tempTotalVariability)
anova(m3)
summary(m3)
par(mfrow = c(2,2))
plot(m3)
```


Calculate anomalies from mean
```{r}
temp20anomaly <- tempDaily20b %>%
  group_by(Season) %>% 
  mutate(meanMax = mean(maxDaily),
         meanMin = mean(minDaily),
         meanMean = mean(meanDaily)) %>%
  ungroup() %>%
  group_by(Season)  %>%
  mutate(maxDiff = maxDaily-meanMax,
         minDiff = minDaily-meanMin,
         meanDiff = meanDaily - meanMean)
  
tempAnomaly20Summary <- temp20anomaly %>%
  group_by(Season, fWY, WY, WYType) %>%
  summarize(meanmaxAnomaly = mean(maxDiff),
            meanminAnomaly = mean(minDiff),
            meanmeanAnomaly = mean(meanDiff),
            sdMax = sd(maxDiff),
            nMax = n(),
            seMax = sdMax/nMax)
```


## Lines
```{r}
# THIS ONE
(line20yr <- ggplot(tempSeason20Summary) + 
  geom_point(aes(x = WY, y = meanMaxTemp, colour = Region), size = 1.5) +
  geom_line(aes(x = WY, y = meanMaxTemp, colour = Region)) +
   geom_errorbar(aes(x = WY, ymin = meanMaxTemp-se, ymax = meanMaxTemp + se, width = 0.2)) +
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Maximum \nDaily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "right",
         axis.title.x = element_blank()))

(line20yr_min <- ggplot(tempSeason20Summary) + 
  geom_point(aes(x = WY, y = meanMinTemp, colour = Region), size = 1.5) +
  geom_line(aes(x = WY, y = meanMinTemp, colour = Region)) +
   geom_errorbar(aes(x = WY, ymin = meanMinTemp-se, ymax = meanMinTemp + se, width = 0.2)) +
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Minimum Daily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "top"))

(line20yrAnom <- ggplot(tempAnomaly20Summary) + 
  geom_point(aes(x = WY, y = meanmaxAnomaly, colour = Region), size = 1.5) +
  geom_line(aes(x = WY, y = meanmaxAnomaly, colour = Region)) +
  # geom_errorbar(aes(x = WY, ymin = meanMaxTemp-se, ymax = meanMaxTemp + se, width = 0.2)) +
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Maximum Daily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "top"))


```

Max
```{r}
tiff(filename=file.path("Figures/TrendsMax20Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=8, res=300, pointsize=12,compression="lzw")
line20yr
dev.off()
```

Min
```{r}
tiff(filename=file.path("Figures/TrendsMin20Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=8, res=300, pointsize=12,compression="lzw")
line20yr_min
dev.off()
```

## Anomalies
```{r}
# THIS ONE
(line20yrAnomMax <- ggplot(tempAnomaly20Summary) + 
  geom_col(aes(x = WY, y = meanmaxAnomaly, fill = WYType), size = 1.5) +
  #geom_errorbar(aes(x = WY, ymin = meanmaxAnomaly-seMax, ymax = meanmaxAnomaly + seMax, width = 0.2)) +
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Anomaly of \nMaximum Daily Temperature (°C)", fill = "Water Year\nType")+
  theme_fig +
   theme(legend.position = "right"))

(line20yrAnomMin <- ggplot(tempAnomaly20Summary) + 
  geom_col(aes(x = WY, y = meanminAnomaly, fill = WYType), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Anomaly of Minimum Daily Temperature (°C)", fill = "Water Year Type")+
  theme_fig +
   theme(legend.position = "top"))

(line20yrAnomMean <- ggplot(tempAnomaly20Summary) + 
  geom_col(aes(x = WY, y = meanmeanAnomaly, fill = WYType), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Anomaly of Mean Daily Temperature (°C)", fill = "Water Year Type")+
  theme_fig +
   theme(legend.position = "top"))
```

```{r}
tiff(filename=file.path("Figures/AnomalyMax20Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=8, res=300, pointsize=12,compression="lzw")
line20yrAnomMax
dev.off()



tiff(filename=file.path("Figures/AnomalyMean20Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=8, res=300, pointsize=12,compression="lzw")
line20yrAnomMean
dev.off()



tiff(filename=file.path("Figures/AnomalyMin20Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=8, res=300, pointsize=12,compression="lzw")
line20yrAnomMin
dev.off()
```

## Combine Line and Anomaly
```{r}
library(patchwork)

tiff(filename=file.path("Figures/Figure_20-year-trends.tiff"), units="in",type="cairo", bg="white", height=7, 
     width=8, res=300, pointsize=10,compression="lzw")
line20yr + line20yrAnomMax + plot_layout(nrow = 2 ) + plot_annotation(tag_levels = "A")
dev.off()
```


## Tile 
```{r}
(max20 <- ggplot(tempDaily20Summary) + geom_tile(aes(x = fWY, y = Region, fill = meanMaxTemp)) + scale_fill_viridis(option = "magma")) + theme_fig

maxdry20 <- ggplot(subset(tempSeason20SummaryStation, Season == "Dry")) + geom_tile(aes(x = fWY, y = Station, fill = meanMaxTemp))  + scale_fill_viridis(option = "plasma")+
  labs(title = "May - September", fill = "Mean Maximum \nWater Temperature\n") + theme_figure

maxwet20 <- ggplot(subset(tempSeason20SummaryStation, Season == "Wet")) + geom_tile(aes(x = fWY, y = Station, fill = meanMaxTemp))  + scale_fill_viridis(option = "mako") + theme_bw() + 
  labs(title = "October - April", fill = "Mean Maximum \nWater Temperature\n") + theme_figure
```

```{r}
grid.arrange(maxdry20, maxwet20, nrow = 2)
```


Scaled and with labels
```{r}
tempSeason20SummaryScale <- tempSeason20SummaryStation %>%
  group_by(Season, Region2, Station) %>%
  mutate(maxScale = scale(meanMaxTemp))  %>%
  mutate(axiscolor = case_when(Region2 == 2 ~ "orange1",
                               Region2 == 3 ~ "firebrick3",
                              Region2 == 4 ~ "navyblue",
                               Region2 == 5 ~ "lightblue4",
                               Region2 == 6 ~ "burlywood3",
                              Region2 == 7 ~ "gray30")) %>%
  ungroup() 

axisColor = c("orange1", "firebrick3", "navyblue", "lightblue4", "burlywood3", "gray30")

axisColor0 = unique(select(tempSeason20SummaryScale, c(Station, axiscolor))) %>%
  arrange(Station)
axisColor = axisColor0$axiscolor


levels(tempSeason20SummaryScale$axiscolor)

(maxwet20S <- ggplot(subset(tempSeason20SummaryScale, Season == "Wet")) + geom_tile(aes(x = fWY, y = Station, fill = maxScale))  + 
    scale_fill_viridis(option = "mako") + 
    theme_bw() + theme_figure + theme(axis.text.y = element_text(size = 10, color = axisColor)) +
  labs(title = "October - April", fill = "Scaled Mean \nMaximum Water \nTemperature\n"))

(maxdry20S <- ggplot(subset(tempSeason20SummaryScale, Season == "Dry")) + geom_tile(aes(x = fWY, y = Station, fill = maxScale))  + scale_fill_viridis(option = "plasma") + 
    theme_bw() + theme_figure + theme(axis.text.y = element_text(size = 10, color = axisColor)) +
  labs(title = "May-September", fill = "Scaled Mean \nMaximum Water \nTemperature\n") )
```

```{r}
tiff(filename=file.path("Figures/Trends20Years_scaled.tiff"), units="in",type="cairo", bg="white", height=7, 
     width=7, res=300, pointsize=12,compression="lzw")
grid.arrange(maxdry20S, maxwet20S, nrow = 2)
dev.off()
```

# 10 year trends
```{r}
tempDaily10b <- tempDaily10 %>%
  mutate(Region2 = ifelse(Region == "Far North", "North Delta", Region),
         Month = month(Date),
         fWY = factor(WY),
         Season = ifelse(Month >4 & Month <10, "Dry Season", "Wet Season")) %>%
  mutate(Region2 = factor(Region2))

tempDaily10Summary <- tempDaily10b %>%
  group_by(fWY, WY, Region, Region2, Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily)) %>%
  ungroup()

tempSeason10SummaryStation <- tempDaily10b %>%
  group_by(Season, fWY, WY, WYType2_Sac, Region, Region2,Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

tempSeason10Summary <- tempDaily10b %>%
  group_by(Season, fWY, WY, Region, Region2) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

tempMonth10SummaryStation <- tempDaily10b %>%
  group_by(Season, Month, fWY, WY, WYType2_Sac, Region, Region2,Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

# variability ---------------------------------------------
tempTotalVariability <- tempDaily10b %>%
  group_by(Station, Season, Region2) %>%
  summarize(sd = sd(maxDaily),
            mean = mean(maxDaily),
            cv = sd/mean)

meanVariabilityBySeasonRegion <- tempTotalVariability %>%
  group_by(Region2, Season) %>%
  summarize(meancv = mean(cv))
```


```{r}
temp10anomaly <- tempDaily10b %>%
  group_by(Season) %>% 
  mutate(meanMax = mean(maxDaily),
         meanMin = mean(minDaily)) %>%
  ungroup() %>%
  group_by(Season)  %>%
  mutate(maxDiff = maxDaily-meanMax,
         minDiff = minDaily-meanMin)
  
tempAnomaly10Summary <- temp10anomaly %>%
  group_by(Season, fWY, WY, WYType2_Sac) %>%
  summarize(meanmaxAnomaly = mean(maxDiff),
            meanminAnomaly = mean(minDiff),
            sdMax = sd(maxDiff)) %>%
  ungroup()
```

## Lines
```{r}
(line10yr <- ggplot(tempSeason10Summary) + 
  geom_point(aes(x = WY, y = meanMaxTemp, colour = Region), size = 2) +
  geom_line(aes(x = WY, y = meanMaxTemp, colour = Region)) +
   geom_errorbar(aes(x = WY, ymin = meanMaxTemp-se, ymax = meanMaxTemp + se, width = 0.2)) +
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 2010, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Maximum Daily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "top"))
```

```{r}
tiff(filename=file.path("Figures/Trends10Years_line.tiff"), units="in",type="cairo", bg="white", height=5.5, 
     width=7, res=300, pointsize=12,compression="lzw")
line10yr
dev.off()
```

## Anomalies
```{r}
tempAnomaly10Summary$Season <- factor(tempAnomaly10Summary$Season, levels = c("Wet Season", "Dry Season"))
(line10yrAnomMax <- ggplot(tempAnomaly10Summary) + 
  geom_col(aes(x = WY, y = meanmaxAnomaly, fill = WYType2_Sac), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
   scale_y_continuous(breaks = seq(-1, 2, 0.5))+
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Maximum Daily Temperature (°C)", fill = "Water Year Type")+
  theme_fig +
   theme(legend.position = "top",
         axis.title.x = element_blank(),
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank()))

(line10yrAnomMin <- ggplot(tempAnomaly10Summary) + 
  geom_col(aes(x = WY, y = meanminAnomaly), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Minimum Daily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "top"))
```

## Plot for interannual variance
```{r}
(varianceplot <-ggplot(tempTotalVariability) + geom_boxplot(aes(Region2, cv, fill = Region2)) + facet_wrap(~Season) + scale_fill_viridis(option = "plasma", discrete = TRUE) + labs(y = "Coefficient of Variation (CV)", fill = "Region") + theme_fig + 
  theme(axis.title.x = element_blank(),                    
        axis.text.x = element_text(angle = 90)))
```

```{r}
tiff(filename=file.path(here::here("Figures/Figure_anomaly_10year.tiff")), units="in",type="cairo", bg="white", height=7, 
     width=8, res=300, pointsize=10,compression="lzw")
line10yrAnomMax
dev.off()

png(filename=file.path("Figures/Figure_Regional_interannual_variance.tiff"), units="in",type="cairo", bg="white", height=5, 
     width=8, res=300, pointsize=10)
varianceplot
dev.off()
```

## Plot for minimum temps
```{r}
tempMonth10SummaryStation %>%
  filter(Season == "Dry Season") %>%
  ggplot() + 
  geom_boxplot(aes(x = Region, y = meanMinTemp, fill = factor(Month)))+ 
   scale_fill_viridis(discrete = TRUE) + 
  theme_fig + 
  theme(axis.title.x = element_blank(),                    
        axis.text.x = element_text(angle = 90))

(minplot <- ggplot(tempMonth10SummaryStation) + geom_point(aes(x = Region, y = meanMinTemp, color = factor(Month))) + facet_wrap(~Season) + 
   scale_color_viridis(discrete = TRUE) + 
  theme_fig + 
  theme(axis.title.x = element_blank(),                    
        axis.text.x = element_text(angle = 90)))
```

