```{r}
library(tidyverse)
library(lubridate)
```

```{r}
load("actiondata.RData")
load("historicaldata.RData")
load("dayflowdata.RData")
```

# Water Quality

```{r}
salinity.data = historical.daily %>%
  filter(
    near(month(Datetime), 7),
    str_detect(Analyte, "Salinity")
  ) %>%
  mutate(
      Year = year(Datetime),
      Month = month(Datetime),
      Day = day(Datetime),
      Analyte = factor(Analyte,
        c("Salinity", "Temperature", "Fluorescence", "Turbidity"),
        c("Salinity (PSU)", "Temperature (\u00B0C)", "Chlorophyll (\u00B5g/L)",
        "Turbidity (NTU)")),
      Station = factor(case_when(
        str_detect(Station, "Collinsville") ~ "River",
        str_detect(Station, "National") ~ "East Marsh",
        str_detect(Station, "Hunter") ~ "West Marsh",
        TRUE ~ NA_character_
      ), c("River", "East Marsh", "West Marsh"))
    ) %>%
    select(Station, Year, Day, Mean)
```

```{r}
salinity.spread = salinity.data %>%
  filter(
#    !(Year %in% c(2014, 2015)),
    Year < 2018
  ) %>%
  mutate(station.day = paste(Station, Day)) %>%
  select(-Station, - Day) %>%
  spread(station.day, Mean) %>%
  as.data.frame()
rownames(salinity.spread) = salinity.spread$Year
salinity.spread["Year"] = NULL
salinity.dist = dist(salinity.spread, "euclidean")
salinity.fit = hclust(salinity.dist, method = "ward.D")
plot(salinity.fit)

#an.years = c(2005L, 2006L, 2017L)
#bn.years = c(2002L, 2009L, 2016L)
```

# Flow

```{r}
flow.data = dayflow %>%
  filter(between(month(Date), 5, 7)) %>%
  arrange(Date) %>%
  group_by(Year) %>%
  mutate(NDOI.cum = cumsum(NDOI)) %>%
  ungroup() %>%
  filter(
    near(Month, 7)
  ) %>%
  mutate(Day = day(Date)) 
```

```{r}
flow.spread = flow.data %>%
  filter(
    Year %in% unique(salinity.data$Year),
    Year < 2018 
  ) %>%
  select(Year, Day, NDOI.cum) %>%
  spread(Day, NDOI.cum) %>%
  as.data.frame()
rownames(flow.spread) = flow.spread$Year
flow.spread["Year"] = NULL
flow.dist = dist(flow.spread, "euclidean")
flow.fit = hclust(flow.dist, method = "median")
plot(flow.fit)

#an.years = c(2005L, 2006L, 2017L)
#bn.years = c(2002L, 2009L, 2016L)
```


# combined

```{r}
combined.spread = cbind(salinity.spread, flow.spread[match(rownames(salinity.spread), rownames(flow.spread))])
combined.dist = dist(combined.spread, "euclidean")
combined.fit = hclust(combined.dist, method = "ward.D")
plot(combined.fit)
```