---
title: "Check_Aerator_RRI"
author: "Catarina Pien"
date: "10/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
```


```{r}
RRI_pred <- read.csv("Data/RRI_Predictions.csv")
Aerator <- read.csv("Data/OxygenData.csv")
RRI <- read.csv("Data/RRI_reldiff.csv")

Aerator$Date <- mdy(Aerator$Date)
RRI$Date <- ymd(RRI$Date)
```

```{r}

join <- left_join(RRI, Aerator) %>%
  mutate(On = ifelse(is.na(Water_Flow_cfs), 0L, -2L),
         Flow = ifelse(is.na(Water_Flow_cfs), 0L, Water_Flow_cfs)) %>%
  group_by(Date, On) %>%
  summarize(meanTempDiff = mean(RelTempDiff),
            sumFlow = sum(Flow)) %>%
  ungroup() %>%
  mutate(Status = ifelse(On == 0, "Off", "On"))

year <- join %>%
  mutate(large = ifelse(meanTempDiff< -0.5, 1L, 0L),
         year = year(Date)) %>%
  group_by(year, large, On) %>%
  summarize(n = n()) %>%
  filter(year != 2012)



ggplot(year, aes(x = large, y = On, fill = n)) + geom_tile()


ggplot(join, aes(x = Date)) + 
  geom_col(aes(y = On), color = "lightblue") + 
  geom_point(aes(y = meanTempDiff), size = 1) +
  scale_x_date(date_breaks = "6 months") +
  labs(y = "Surface-Bottom Difference") +
  theme_bw() + theme(axis.text.x = element_text(angle = 90))

```

```{r}
ggplot(filter(join, month(Date)>6 & month(Date)<11), aes(x = sumFlow, y = meanTempDiff)) + geom_point() + theme_bw()

ggplot(filter(join, month(Date)>6 & month(Date)<11), aes(Status, meanTempDiff)) + geom_boxplot() + theme_bw()
```

