---
title: "EcoThresholds"
author: "Catarina Pien"
date: "10/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in data
```{r}
setwd("C:/Users/cpien/OneDrive - California Department of Water Resources/Work/ClimateChange/R_code/TempSynthesis/")

# tempFilt <- readRDS("Data/tempFilt.rds") 
# tempToUse <- readRDS("Data/temp10years_20200922.rds")
# tempAn <- readRDS("Data/tempAnnual.rds")
tempMon <- readRDS("Data/tempMonthly.rds")
tempDaily <- readRDS("Data/tempDaily.rds")
# tempHeat <- readRDS("Data/heatstressDaily.rds")
```

Code to make sure every month has data
```{r nMon}
# Filter to only data that has temps from every month so as not to skew the data that only has part of the year represented.
nMon <- tempMon %>% group_by(Station, WY) %>%
  summarize(nMon = n())

nMon$WY <- as.numeric(nMon$WY)
```

# Filter 2009-2019
```{r}
tempDaily$Month <- month(tempDaily$Date)
tempDailyM <- left_join(tempDaily, nMon) %>%
  filter(nMon == 12) %>%
  filter(WY>2008 & WY<2020)
```

## Winter/Spring

### Delta Smelt 
Spawning window for Delta Smelt: Temperatures between 15-20C in the spring
* March - June? Or limit to March-May?
Regions of interest: 
```{r}
Spring <- tempDailyM %>%
  mutate(Month = month(Date)) %>%
  filter(Month %in% c(3,4,5,6))

SpringThr <- Spring %>%
  group_by(Station, WY, Date) %>%
  mutate(Spawn_DSM = ifelse(maxDaily > 15 & minDaily < 20, "Y", "N")) %>% 
  ungroup() %>%
  group_by(Region, Station, WY, Spawn_DSM) %>%
  summarize(nDays = n()) %>%
  ungroup() %>%
  group_by(Station)%>%
  mutate(nD_scale = scale(nDays)) %>%
  arrange(Region)

```

# Heat maps
```{r}
# Absolute temps
plot <- ggplot(SpringThr) +
  geom_tile(aes(x = ordered(WY), y = Station, fill = nDays) ) +
  scale_fill_viridis(option = "cividis") + theme_minimal() + 
  labs(title = "DSM Spawning Days") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title = element_text(size = 12))
ggplotly(plot)

# Scaled 
plot2 <- ggplot(SpringThr) +
  geom_tile(aes(x = ordered(WY), y = Station, fill = nD_scale) ) +
  scale_fill_viridis(option = "cividis") + theme_minimal() + 
  labs(title = "DSM Spawning Days") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title = element_text(size = 12))
ggplotly(plot2)


```

Day that spawning window starts 
```{r}
Spring$yday <- yday(Spring$Date)
SpringSp <- filter(Spring, minDaily>14.9 & maxDaily<20.1)
SpringSp2 <- SpringSp %>%
  group_by(WY, Region) %>%
  filter(Region %in% c("North Delta", "Sac River", "Suisun Bay", "Suisun Marsh")) %>%
  summarize(DayI = first(yday),
            DayF = last(yday),
            Days = DayF-DayI)


# Number of days spawning window by region
ggplot(SpringSp2) +
  geom_col(aes(x = ordered(WY), y = Days, fill = Region), position = position_dodge2()) + scale_fill_viridis(option = "viridis", discrete = TRUE) + theme_bw()

# Shift in timing by year (yday spawning)
ggplot(SpringSp, aes(x = yday, y = maxDaily, color = ordered(WY)), alpha = 0.6) + geom_point() + scale_color_viridis(option = "magma", discrete = TRUE) + theme_bw() 

# Spawning window by region
ggplot(SpringSp2) + 
  geom_linerange(aes(xmin = DayI, xmax = DayF, y = ordered(WY), color = Region), alpha = 0.9,  size = 3 ) +
    geom_point(aes(x = DayI, y = ordered(WY), color = Region), size = 4) +
  geom_point(aes(x = DayF, y = ordered(WY), color = Region), size = 4) +
  labs(x = "yday", title = "Spawning Window for Delta Smelt by Region") + scale_color_viridis(option = "viridis", discrete = TRUE) + theme_minimal() 


```

### Salmon
Rearing temperatures
Regions of interest: 


### Splittail 

