---
title: "FiguresForTrends"
author: "Catarina Pien"
date: "1/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(viridis)
```

```{r}
theme_fig = theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, size = 14),
        strip.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        legend.text = element_text(size =10),
        legend.title = element_text(size = 11))

theme_figure <-  theme_bw() + theme(axis.title.y = element_blank(),                                 axis.title.x = element_blank(),legend.position = "right",
                                     axis.text.x = element_text(size = 10, angle= 90),
                                     axis.text.y = element_text(size = 10),
                                    legend.text = element_text(size = 10),
                                    legend.title = element_text(size = 10.5),
                                    plot.title = element_text(hjust = 0.5)) 
```

```{r}
# tempDaily20 <- readRDS(here::here("Data/tempDaily20yr_20220125.rds")) %>%
#   mutate(Region = as.character(Region)) %>%
#   mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
#          Region = replace(Region, Region == "San Joaquin", "Central")) %>%
#   rename(WYType = WYType2_Sac)

tempDaily10 <- readRDS(here::here("manuscript_code/Data/tempDaily.rds"))%>%
  mutate(Region = as.character(Region)) %>%
  mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
         Region = replace(Region, Region == "San Joaquin", "Central"))

LatLon <- read.csv(here::here("manuscript_code/Data/StationsMetadata.csv"))

Regions <- read.csv(here::here("manuscript_code/Data/stations_w_regions_20230601.csv")) %>%
  mutate(Region = as.character(Regions)) %>%
  mutate(Region = replace(Region, Region == "Sac River", "Confluence"),
         Region = replace(Region, Region == "San Joaquin", "Central"))
```

Make supplemental tables
```{r}
summary10 <- tempDaily10 %>%
  group_by(Station) %>%
  summarize(StartDateAnalysis = first(Date),
            EndDateAnalysis = last(Date)) %>%
  left_join(LatLon %>% select(Station, StationName, Agency, Latitude, Longitude, HabitatType)) %>%
  left_join(Regions %>% select(Station, Region)) %>%
  select(Station, StationName, Region, Latitude, Longitude, StartDateAnalysis, EndDateAnalysis, Agency, HabitatType)

# write_csv(summary10, "Tables/Stations_included_10year.csv")
```

# 10 year trends
```{r}
tempDaily10b <- tempDaily10 %>%
  mutate(Region2 = ifelse(Region == "Far North", "North Delta", Region),
         Month = month(Date),
         fWY = factor(WY),
         Season = ifelse(Month >4 & Month <10, "Dry Season", "Wet Season")) %>%
  mutate(Region2 = factor(Region2))

tempDaily10Summary <- tempDaily10b %>%
  group_by(fWY, WY, Region, Region2, Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily)) %>%
  ungroup()

tempSeason10SummaryStation <- tempDaily10b %>%
  group_by(Season, fWY, WY, WYType2_Sac, Region, Region2,Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

tempSeason10Summary <- tempDaily10b %>%
  group_by(Season, fWY, WY, Region, Region2) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))

tempMonth10SummaryStation <- tempDaily10b %>%
  group_by(Season, Month, fWY, WY, WYType2_Sac, Region, Region2,Station) %>%
  summarize(meanMaxTemp = mean(maxDaily),
            meanMinTemp = mean(minDaily),
            sd = sd(maxDaily),
            n = n(),
            se = sd/sqrt(n))


```

## Anomaly
```{r}
temp10anomaly <- tempDaily10b %>%
  group_by(Season) %>% 
  mutate(meanMax = mean(maxDaily),
         meanMin = mean(minDaily)) %>%
  ungroup() %>%
  group_by(Season)  %>%
  mutate(maxDiff = maxDaily-meanMax,
         minDiff = minDaily-meanMin)
  
tempAnomaly10Summary <- temp10anomaly %>%
  group_by(Season, fWY, WY, WYType2_Sac) %>%
  summarize(meanmaxAnomaly = mean(maxDiff),
            meanminAnomaly = mean(minDiff),
            sdMax = sd(maxDiff)) %>%
  ungroup()
```

## Anomalies
```{r}
tempAnomaly10Summary$Season <- factor(tempAnomaly10Summary$Season, levels = c("Wet Season", "Dry Season"))
(line10yrAnomMax <- ggplot(tempAnomaly10Summary) + 
  geom_col(aes(x = WY, y = meanmaxAnomaly, fill = WYType2_Sac), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
   scale_y_continuous(breaks = seq(-1, 2, 0.5))+
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Maximum Daily Temperature (°C)", fill = "Water Year Type")+
  theme_fig +
   theme(legend.position = "top",
         axis.title.x = element_blank(),
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank()))

(line10yrAnomMin <- ggplot(tempAnomaly10Summary) + 
  geom_col(aes(x = WY, y = meanminAnomaly), size = 1.5) +
 
  facet_grid(Season~., scales = "free_y") +
  scale_x_continuous(breaks = seq(from = 1999, to = 2019, by = 1)) +
  scale_colour_viridis(discrete = TRUE) +
  labs(x = "Water Year", y = "Mean Minimum Daily Temperature (°C)")+
  theme_fig +
   theme(legend.position = "top"))
```

## Plot for interannual variance

```{r}
# variability ---------------------------------------------
tempTotalVariability <- tempDaily10b %>%
  group_by(Station, Season, Region2) %>%
  summarize(sd = sd(maxDaily),
            mean = mean(maxDaily),
            cv = sd/mean)

meanVariabilityBySeasonRegion <- tempTotalVariability %>%
  group_by(Region2, Season) %>%
  summarize(meancv = mean(cv))
```

```{r}
(varianceplot <-ggplot(tempTotalVariability) + geom_boxplot(aes(Region2, cv, fill = Region2)) + facet_wrap(~Season) + scale_fill_viridis(option = "plasma", discrete = TRUE) + labs(y = "Coefficient of Variation (CV)", fill = "Region") + theme_fig + 
  theme(axis.title.x = element_blank(),                    
        axis.text.x = element_text(angle = 90)))
```

```{r}
# png(filename=file.path(here::here("manuscript_code/Figures/Figure_anomaly_10year.tiff")), units="in",type="cairo", bg="white", height=7, 
#      width=8, res=300, pointsize=10,compression="lzw")
# line10yrAnomMax
# dev.off()

png(filename=file.path("manuscript_code/Figures/Figure_Regional_interannual_variance.png"), units="in",type="cairo", bg="white", height=5, 
     width=8, res=300, pointsize=10)
varianceplot
dev.off()
```

